"""Alert memo agent: retrieval-augmented analyst notes for every alert.

Mirrors how AML/trade-surveillance teams deploy LLMs — an investigator
copilot that drafts the case narrative from structured evidence plus
retrieved context (patch notes, community reports). Three design rules:
  1. structured evidence in, structured memo out (fixed sections),
  2. retrieval is cited inline so claims are checkable,
  3. a deterministic offline template is the default; the LLM path activates
     only when ANTHROPIC_API_KEY is set, and any failure falls back silently.
"""
from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path

import httpx
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from . import config


# ----------------------------- retrieval -----------------------------------
class TfidfRetriever:
    """Paragraph-level TF-IDF retrieval over data/corpus/*.md. Deliberately
    dependency-light; swap in embeddings + a vector DB without touching
    callers (query() is the contract)."""

    def __init__(self, corpus_dir: Path | None = None):
        corpus_dir = corpus_dir or config.CORPUS_DIR
        self.docs: list[tuple[str, str]] = []  # (source_file, paragraph)
        for f in sorted(corpus_dir.glob("*.md")):
            for para in [p.strip() for p in f.read_text(encoding="utf-8").split("\n\n") if p.strip()]:
                self.docs.append((f.name, para))
        texts = [p for _, p in self.docs] or ["empty corpus"]
        self.vec = TfidfVectorizer(stop_words="english")
        self.mat = self.vec.fit_transform(texts)

    def query(self, text: str, k: int = 3) -> list[dict]:
        if not self.docs:
            return []
        sims = cosine_similarity(self.vec.transform([text]), self.mat)[0]
        idx = np.argsort(-sims)[:k]
        return [{"source": self.docs[i][0], "text": self.docs[i][1],
                 "score": float(sims[i])} for i in idx if sims[i] > 0.01]


# ----------------------------- memo rendering --------------------------------
def _fmt_ts(ts: int) -> str:
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def build_query(alert: dict) -> str:
    kind = alert.get("kind_guess") or alert.get("top_detector", "anomaly")
    return f"{kind} grand exchange price volume spike manipulation game update"


def render_memo(alert: dict, item_name: str, evidence: dict,
                retrieved: list[dict]) -> str:
    dur_min = (alert["ts_end"] - alert["ts_start"]) // 60 + 5
    ctx = "\n".join(
        f"> [{r['source']}] {r['text'][:300]}" for r in retrieved
    ) or "> (no relevant context retrieved)"
    impact = evidence.get("impact_note", "n/a")
    return f"""# Alert memo — {item_name} (item {alert['item_id']})

**Window:** {_fmt_ts(alert['ts_start'])} → {_fmt_ts(alert['ts_end'])} ({dur_min} min)
**Ensemble score:** {alert['score']:.2f} · **Primary signal:** {alert.get('top_detector', 'n/a')}
**Hypothesis:** {alert.get('kind_guess', 'unclassified anomaly')}

## What happened
Peak volume z-score {evidence.get('vol_z_peak', 0):.1f}, 30-min return
{evidence.get('ret6_peak', 0) * 100:.1f}%, price at {evidence.get('px_ratio_peak', 1):.1f}x its
rolling median, spread z {evidence.get('spread_z_peak', 0):.1f}.

## Counterfactual impact
{impact}

## Plausible benign explanations
- Announced game update repricing (checked: {'YES — inside update window' if evidence.get('near_update') else 'no update within suppression window'})
- Organic news/content-creator demand shock (volume usually broad, two-sided)
- Data artifact (RuneLite coverage gap; check gap report)

## Retrieved context
{ctx}

## Suggested action
{'Review and likely dismiss — benign repricing pattern.' if evidence.get('near_update') else 'Escalate for review: pattern matches ' + str(alert.get('kind_guess', 'anomaly')) + ' signature; pull trader-level data if available.'}

*Generated by GE-Sentinel ({'LLM-assisted' if evidence.get('llm') else 'deterministic template'}); evidence payload attached.*
"""


def llm_polish(memo_md: str, alert: dict) -> str | None:
    """Optional: rewrite the template memo via the Anthropic API. Returns None
    on any failure so the deterministic memo always survives."""
    if not config.ANTHROPIC_API_KEY:
        return None
    try:
        r = httpx.post(
            config.ANTHROPIC_URL,
            headers={"x-api-key": config.ANTHROPIC_API_KEY,
                     "anthropic-version": "2023-06-01",
                     "content-type": "application/json"},
            json={"model": config.ANTHROPIC_MODEL, "max_tokens": 700,
                  "messages": [{"role": "user", "content":
                      "Rewrite this market-surveillance alert memo to be tighter and "
                      "more decision-ready. Keep every number and section, keep the "
                      "citation lines verbatim, do not invent facts.\n\n" + memo_md}]},
            timeout=30.0,
        )
        r.raise_for_status()
        parts = r.json().get("content", [])
        text = "\n".join(p.get("text", "") for p in parts if p.get("type") == "text").strip()
        return text or None
    except Exception:
        return None


def write_memos(alerts: list[dict], evidences: dict[int, dict],
                item_names: dict[int, str], out_dir: Path | None = None,
                retriever: TfidfRetriever | None = None, top_n: int = 5) -> list[str]:
    out_dir = out_dir or config.MEMO_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    retriever = retriever or TfidfRetriever()
    paths = []
    for rank, a in enumerate(alerts[:top_n], 1):
        ev = evidences.get(id(a), evidences.get(rank - 1, {}))
        retrieved = retriever.query(build_query(a))
        memo = render_memo(a, item_names.get(a["item_id"], str(a["item_id"])), ev, retrieved)
        polished = llm_polish(memo, a)
        if polished:
            ev["llm"] = True
            memo = polished + "\n\n---\n*LLM-polished; deterministic original retained in evidence.*"
        p = out_dir / f"alert_{rank:02d}_item{a['item_id']}_{a['ts_start']}.md"
        p.write_text(memo, encoding="utf-8")
        (out_dir / f"alert_{rank:02d}_evidence.json").write_text(
            json.dumps({**a, "evidence": ev, "generated_ts": int(time.time())}, indent=2),
            encoding="utf-8")
        paths.append(str(p))
    return paths
